# Generated by Django 5.1.4 on 2025-01-12 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_rename_phone_donor_phone_number_alter_donor_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='sharing.donor')),
            ],
        ),
    ]
